### ISSUE TITLE
Add a Global Shortcut

### ISSUE THREAD

**Issue by katungi** [katungi/pasta#11]
We should add a global shortcut like `cmd + opt + V`  to toggle on and off the pasta window

Resources: https://tauri.app/v1/api/js/globalshortcut/
Resources: https://stackoverflow.com/questions/78056795/how-to-re-open-a-minimized-tauri-application-with-keyboard-shortcuts#:~:text=2%20Answers&text=Since%20the%20document%20no%20longer,();%20%7D%2C%20%5B%5D);

**Comment by GrishonNganga** [comment]
Exactly what I was looking for. 

I thought I was the one doing the wrong thing. I see on the project readme you have Shift Cmd V as well. Is there something I am not getting right?

**Comment by katungi** [comment]
Hey @GrishonNganga , I had not finished on the feature. I was waiting for the v2 of Tauri to be stable so I can release that feature. That along with other fixes to annoying mac os behaviors will be in the next release soon.

**Comment by katungi** [comment]
The new release V0.1.2 comes with a Global shortcut "Cms+Shift+V".

Caveat - the app needs to be launched first and running on the background.
